# Generated by Django 6.0.2 on 2026-02-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Studentname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Student last name')),
                ('group_name', models.CharField(max_length=100, verbose_name='Student group')),
            ],
        ),
    ]
